### ISSUE TITLE
MIUI14 cannot mount /product/pangu/ to use NFC

### ISSUE THREAD

**Issue by nymanyim** [HuskyDG/magic_overlayfs#16]
![Screenshot_2023-04-10-17-41-08-406_bin mt plus](https://user-images.githubusercontent.com/103242499/230877271-db9cdb10-3347-4d67-9f29-e792633a43b0.jpg)

Miui14 mounts nfc to /system/product through this folder /product/pangu/, so it should not be moved.

_Originally posted by @cy12300 in https://github.com/HuskyDG/magic_overlayfs/issues/8#issuecomment-1501616904_

**Comment by nymanyim** [comment]
[overlayfs.log](https://github.com/HuskyDG/magic_overlayfs/files/11591895/overlayfs.log)

**Comment by nymanyim** [comment]
@HuskyDG

**Comment by nymanyim** [comment]
What was the problem that caused the NFC to malfunction after starting the magick_overlays.

**Comment by nymanyim** [comment]
Cancel magick_overlays. NFC is in its normal state

**Comment by nymanyim** [comment]
[mounts.txt](https://github.com/HuskyDG/magic_overlayfs/files/11594681/mounts.txt)

**Comment by nymanyim** [comment]
`OVERLAY_MODE=2` , same thing

**Comment by 4tomson** [comment]
confirm. mirpay does not work. this is a Russian NFC application. I think the reason is the same. miui 14

**Comment by 4tomson** [comment]
Default FirebaseApp is not initialized in this process com.example.vvvv. Make sure to call FirebaseApp.initializeApp(Context) first.

Error like this

**Comment by 4tomson** [comment]
It's look like Woking with this version

**Comment by 4tomson** [comment]
[log.zip](https://github.com/HuskyDG/magic_overlayfs/files/11739163/log.zip)

**Comment by nymanyim** [comment]
[overlayfs.log](https://github.com/HuskyDG/magic_overlayfs/files/11777816/overlayfs.log)
NFC invalid

**Comment by nymanyim** [comment]
[overlayfs(1).log](https://github.com/HuskyDG/magic_overlayfs/files/11778621/overlayfs.1.log)
This is v3.1.2

**Comment by nymanyim** [comment]
NFC invalid

**Comment by 4tomson** [comment]
Error always, when ksu unmount true
With mode=2 too

**Comment by nymanyim** [comment]
OVERLAY_MODE=2 , same thing

**Comment by nymanyim** [comment]
[overlayfs.log](https://github.com/HuskyDG/magic_overlayfs/files/11790450/overlayfs.log)
don't working, v3.1.3

**Comment by 4tomson** [comment]
For me too!
Nothing change

**Comment by nymanyim** [comment]
[2_overlayfs.log](https://github.com/HuskyDG/magic_overlayfs/files/11799346/2_overlayfs.log)

**Comment by nymanyim** [comment]
[3_overlayfs.log](https://github.com/HuskyDG/magic_overlayfs/files/11811721/3_overlayfs.log)

**Comment by nymanyim** [comment]
This issue has been resolved in the latest version
