### ISSUE TITLE
Cameras Failing after Installation - Galaxy Tab S8+

### ISSUE THREAD

**Issue by k0mraid3** [HuskyDG/magic_overlayfs#21]
After Install, or any time the module is enabled, the Cameras, both front and rear, fail with a popup of "Camera Failed". I was not able to get alot of meaningful info via logcat, but i did see "cameraxservice" log something close to "Camera failed due to serious error!" and another entry talking about "Camera has run out of memory" which i found strange, ill attempt to find better logs for this issue. 
Interestingly enough, the issue goes away when module is disabled and device reboot so unsure if this is security related or error
Any ideas on your end wth is going on?
No other Modules are installed aside from systemless hosts and SELinux set to permissive everything else is stock
Device does use F2FS for /system. (and others)

Otherwise module works as expected.

**Comment by k0mraid3** [comment]
Wonder if this issue is coming from /system/cameradata/camera-feature.xml not being properly processed?

**Comment by Akiln7** [comment]
Set OVERLAY_LEGACY_MOUNT=false in mode.sh

**Comment by k0mraid3** [comment]
> Set OVERLAY_LEGACY_MOUNT=true in mode.sh

No way! Thats all it was? haha i was full on debugging camera haha. Thanks guys!

**Comment by k0mraid3** [comment]
> Set OVERLAY_LEGACY_MOUNT=true in mode.sh

Just for the record, in case this issue pops up again, i did install the update, but i still had to set this in mode.sh and reboot. Cameras and all else is happy again.
