### ISSUE TITLE
3.1.3 not working and 3.2 causes bootloop

### ISSUE THREAD

**Issue by Yervant7** [HuskyDG/magic_overlayfs#27]
[overlayfs.log](https://github.com/HuskyDG/magic_overlayfs/files/11944386/overlayfs.log)
This log is from 3.1.3
My kernel is 5.10.66
Kernelsu version 11041 kernel
Manager 11070

**Comment by Yervant7** [comment]
So on my device v3.2 doesn't bootloop the installation is that what deleting these lines will solve?
In v3.2 for me it happened that I installed a module with support for Magic overlayfs and bootlooped

**Comment by Yervant7** [comment]
So on my device v3.2 doesn't bootloop the installation is that what deleting these lines will solve?
In v3.2 for me it happened that I installed a module with support for Magic overlayfs and bootlooped rebooted in recovery and an error android rescue party appear I don't know if this is magic overlayfs bug or ksu bug the message of error in TWRP: 
set_sepolicy_error:/data/extm

**Comment by RashadGasimly** [comment]
Same issue just works on v3.1.2 and above versions
