### ISSUE TITLE
Everything reverts back after disabling module

### ISSUE THREAD

**Issue by aptop6** [HuskyDG/magic_overlayfs#31]
Hey brother. 
I want to make chages made by module(deleting something) permanent even after disabling module. How would I do that?

**Comment by chiteroman** [comment]
Flash this in TWRP: https://github.com/MehrojOfficial/systemRW-modded

Your system now can remount as RW even without Magisk

**Comment by aptop6** [comment]
> Flash this in TWRP: https://github.com/MehrojOfficial/systemRW-modded
> 
> Your system now can remount as RW even without Magisk

Thankyou brother. I was actually browsing that xda thread but the author got banned and that's how I ended here trying to find a different solution to make /system RW.

**Comment by mskonovalov** [comment]
> Flash this in TWRP: https://github.com/MehrojOfficial/systemRW-modded
> 
> Your system now can remount as RW even without Magisk

This repo is deleted :(
Any alternative?

**Comment by chiteroman** [comment]
> > Flash this in TWRP: https://github.com/MehrojOfficial/systemRW-modded
> > Your system now can remount as RW even without Magisk
> 
> This repo got deleted :( Any alternative?

https://www.systemrw.com/download.php

Use "[Official SYSTEM-RW v1.41 by lebigmac for Samsung Galaxy S23 Ultra and other devices](https://mega.nz/file/TQ42WApL#ky3OzPwEKQeKrFGJYygqEr07zsidEqYAd7lSu9-ceEM)"
