### ISSUE TITLE
/apex/com.android.art/lib64  read only.

### ISSUE THREAD

**Issue by junknet** [HuskyDG/magic_overlayfs#36]
What configuration is needed to make this folder writable?

**Comment by WindySha** [comment]
Add /apex wo't work for me, these paths are Read Only:

/apex/com.android.art
/system/bin

How to fix it?

**Comment by junknet** [comment]
> Add /apex wo't work for me, these paths are Read Only:
> 
> /apex/com.android.art /system/bin
> 
> How to fix it?

https://github.com/junknet/magic_overlayfs
